name: LinkSentinel
description: Validate links in Markdown and reStructuredText docs
inputs:
  path:
    description: "Directory to scan for links"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - run: pip install requests
      shell: bash
    - run: python ${{ github.action_path }}/link_validator.py ${{ inputs.path }}
      shell: bash
