name: LinkSentinel
description: Validate links in Markdown and reStructuredText docs

inputs:
  path:
    description: "Directory to scan for links"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install Rye
      shell: bash
      run: |
        curl -sSf https://rye.astral.sh/get | bash -s -- --yes
        echo "$HOME/.rye/shims" >> $GITHUB_PATH
        echo "export PATH=$HOME/.rye/shims:$PATH" >> $GITHUB_ENV

    - name: Install dependencies
      shell: bash
      run: |
        export PATH="$HOME/.rye/shims:$PATH"
        rye sync --no-venv

    - name: Run link validator
      shell: bash
      run: |
        export PATH="$HOME/.rye/shims:$PATH"
        python ${{ github.action_path }}/linksentinel/link_validator.py ${{ inputs.path }}
