name: LinkSentinel
description: Validate links in Markdown and reStructuredText docs

inputs:
  path:
    description: "Directory to scan for links"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Download Rye prebuilt binary
      shell: bash
      run: |
        mkdir -p "$HOME/.rye"
        curl -L https://github.com/astral-sh/rye/releases/latest/download/rye-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C "$HOME/.rye"
        echo "$HOME/.rye" >> $GITHUB_PATH
        echo "export PATH=$HOME/.rye:$PATH" >> $GITHUB_ENV

    - name: Install dependencies from pyproject.toml
      shell: bash
      run: |
        rye self install --yes
        rye sync --no-venv

    - name: Run link validator
      shell: bash
      run: |
        python ${{ github.action_path }}/linksentinel/link_validator.py ${{ inputs.path }}
