name: LinkSentinel
description: Validate links in Markdown and reStructuredText docs

inputs:
  path:
    description: "Directory to scan for links"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Download and install Rye binary (prebuilt)
      shell: bash
      run: |
        set -e
        RYE_VERSION=$(curl -s https://api.github.com/repos/astral-sh/rye/releases/latest | grep '"tag_name":' | head -1 | cut -d '"' -f 4 | tr -d '\r\n')
        echo "Using Rye version: $RYE_VERSION"
        curl -L "https://github.com/astral-sh/rye/releases/download/${RYE_VERSION}/rye-x86_64-unknown-linux-gnu.tar.gz" -o rye.tar.gz
        file rye.tar.gz
        mkdir -p "$HOME/.rye"
        tar -xzf rye.tar.gz -C "$HOME/.rye"
        echo "$HOME/.rye" >> $GITHUB_PATH
        echo "export PATH=$HOME/.rye:$PATH" >> $GITHUB_ENV

    - name: Install dependencies from pyproject.toml
      shell: bash
      run: |
        rye self install --yes
        rye sync --no-venv

    - name: Run link validator
      shell: bash
      run: |
        python ${{ github.action_path }}/linksentinel/link_validator.py "${{ inputs.path }}"
