name: LinkSentinel
description: Validate links in Markdown and reStructuredText docs

inputs:
  path:
    description: "Directory to scan for links"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Setup Rye and install dependencies
      shell: bash
      run: |
        curl -sSf https://rye-up.com/get | bash
        export PATH="$HOME/.rye/shims:$PATH"
        ~/.rye/shims/rye self install
        ~/.rye/shims/rye sync --no-venv
        echo "$HOME/.rye/shims" >> $GITHUB_PATH

    - name: Run link validator
      shell: bash
      run: |
        python ${{ github.action_path }}/linksentinel/link_validator.py ${{ inputs.path }}
