name: LinkSentinel
description: Validate links in Markdown and reStructuredText docs

inputs:
  path:
    description: "Directory to scan for links"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Setup Rye and install deps
      shell: bash
      run: |
        curl -sSf https://rye-up.com/get | bash
        export PATH="$HOME/.rye/shims:$PATH"
        rye self install
        rye sync --no-venv

    - name: Run link validator
      shell: bash
      run: |
        export PATH="$HOME/.rye/shims:$PATH"
        python ${{ github.action_path }}/linksentinel/link_validator.py ${{ inputs.path }}
