name: LinkSentinel
description: Validate links in Markdown and reStructuredText docs

inputs:
  path:
    description: "Directory to scan for links"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install pdm
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pdm

    - name: Install dependencies from pyproject.toml using pdm
      shell: bash
      run: |
        PDM_IGNORE_VENV=1 pdm install

    - name: Run link validator
      shell: bash
      run: |
        python ${{ github.action_path }}/linksentinel/link_validator.py "${{ inputs.path }}"

branding:
  icon: "check-circle"
  color: "blue"
