name: LinkSentinel
description: Validate links in Markdown and reStructuredText docs

inputs:
  path:
    description: "Directory to scan for links"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install Rye
      run: |
        curl -sSf https://rye-up.com/get | bash
        export PATH="$HOME/.rye/shims:$PATH"
        echo "$HOME/.rye/shims" >> $GITHUB_PATH
      shell: bash

    - name: Install dependencies
      run: rye sync --no-venv
      shell: bash

    - run: python ${{ github.action_path }}/linksentinel/link_validator.py ${{ inputs.path }}
      shell: bash
